{% macro get_high_water_mark(column_name, predicate=none, warehouse_size='xs', model_name=this.name) %}
    {{ return(adapter.dispatch('get_high_water_mark', 'dbt_macro_polo')(column_name, predicate, warehouse_size, model_name)) }}
{% endmacro %}

{% macro snowflake__get_high_water_mark(column_name, predicate=none, warehouse_size='xs', model_name=this.name) %}

    {% set macro_polo = var('macro_polo', {}) %}
    {% set model_id = this.schema ~ "." ~ this.name if this else 'unknown_model' %}
    {% set macro_name = 'get_high_water_mark' %}

    {# Input validation #}
    {% if not column_name %}
        {% set msg = "Configuration Error: column_name is required." %}
        {{ dbt_macro_polo.log_event(message=msg, level='ERROR', model_id=model_id, macro_name=macro_name) }}
    {% endif %}

    {% if execute %}

        {# Cache handling #}
        {% set state_key = '_macro_polo_hwm_' ~ model_id | replace('.', '_') ~ '_' ~ column_name  ~ ('_' ~ predicate | replace(' ', '_') if predicate is not none else '') %}
        {% set state_value = dbt_macro_polo.get_runtime_state(state_key) %}
    
        {% if state_value %}
            {{ dbt_macro_polo.log_event(message="Resolved high water mark from runtime state", model_id=model_id, status=state_value | upper, macro_name=macro_name) }}
            {{ return("'" ~ state_value ~ "'") }}
        {% endif %}

        {# Warehouse allocation #}
        {% set warehouse = dbt_macro_polo.provision_compute(warehouse_size) %}
        {% if not warehouse %}
            {{ dbt_macro_polo.log_event(message="Failed to allocate warehouse", level='ERROR', model_id=model_id, macro_name=macro_name) }}
        {% endif %}

        {# Get relation with validation #}
        {% set relation = adapter.get_relation(this.database, this.schema, model_name) if model_name is not none else this %}
        {% if not relation %}
            {{ dbt_macro_polo.log_event(message="Relation not found: " ~ model_name, level='ERROR', model_id=model_id, macro_name=macro_name) }}
        {% endif %}

        {# Build and execute query #}
        {% set query %}
            /* Query generated by {{ macro_name }} macro */
            select coalesce(max({{ column_name }}), '0') as max_value
            from {{ relation }}
            {% if predicate %}
                where {{ predicate }}
            {% endif %}
        {% endset %}

        {# Set warehouse and execute query #}
        {% do run_query('use warehouse ' ~ warehouse) %}
        {% set result = run_query(query) %}
        {# Reset warehouse otherwise dbt will use the previous warehouse size #}
        {% do run_query('use warehouse ' ~ target.warehouse) %}

        {% if not result %}
            {{ dbt_macro_polo.log_event(message="Query execution failed", level='ERROR', model_id=model_id, macro_name=macro_name) }}
        {% endif %}

        {# Process and validate result #}
        {% set max_value = result.columns[0].values()[0] %}
        {% if max_value is none %}
            {{ dbt_macro_polo.log_event(message="No timestamp value returned", level='ERROR', model_id=model_id, macro_name=macro_name) }}
        {% endif %}

        {# Cache and return result #}

        {{ dbt_macro_polo.log_event(message="Saving high water mark '" ~ max_value ~ "' to runtime state with key '" ~ state_key ~ "'", model_id=model_id, level='DEBUG', macro_name=macro_name) }}
        {# Update: Use runtime_state instead of cache #}
        {% do macro_polo.get('runtime_state', {}).update({state_key: max_value}) %}
        {{ dbt_macro_polo.log_event(message="Resolved high water mark", model_id=model_id, status=max_value | upper, macro_name=macro_name) }}
        {{ return("'" ~ max_value ~ "'") }}

    {% endif %}

{% endmacro %}
