{% macro get_high_water_mark(column_name, predicate=none, warehouse_size='xs', model_name=this.name) %}
    {#
    Retrieves the maximum value of a column from a relation (High Water Mark).
    Uses a specific warehouse size for the query and caches the result.

    Args:
        column_name (str): The column to find the max value for.
        predicate (str, optional): SQL where clause filter.
        warehouse_size (str, optional): Warehouse size to use. Defaults to 'xs'.
        model_name (str, optional): The model/relation name. Defaults to this.name.
    
    Returns:
        str: The maximum value wrapped in quotes.
    #}
    {{ return(adapter.dispatch('get_high_water_mark', 'dbt_macro_polo')(column_name, predicate, warehouse_size, model_name)) }}
{% endmacro %}

{% macro snowflake__get_high_water_mark(column_name, predicate=none, warehouse_size='xs', model_name=this.name) %}

    {% set macro_polo = var('macro_polo', {}) %}
    {% set model_id = this.schema ~ "." ~ this.name if this else 'unknown_model' %}
    {% set macro_name = 'get_high_water_mark' %}

    {# Input validation #}
    {% if not column_name %}
        {% set msg = "Configuration Error: column_name is required." %}
        {{ dbt_macro_polo.log_event(message=msg, level='ERROR', model_id=model_id, macro_name=macro_name) }}
    {% endif %}

    {% if execute %}

        {# Cache handling #}
        {% set state_key = '_macro_polo_hwm_' ~ model_id | replace('.', '_') ~ '_' ~ column_name  ~ ('_' ~ predicate | replace(' ', '_') if predicate is not none else '') %}
        {% set state_value = dbt_macro_polo.get_runtime_state(state_key) %}
    
        {% if state_value %}
            {{ dbt_macro_polo.log_event(
                message="Resolved high water mark from runtime state", 
                model_id=model_id, 
                status=state_value | upper, 
                macro_name=macro_name
            ) }}
            {{ return("'" ~ state_value ~ "'") }}
        {% endif %}

        {# Warehouse allocation #}
        {% set warehouse = dbt_macro_polo.provision_compute(warehouse_size) %}
        {% if not warehouse %}
            {{ dbt_macro_polo.log_event(
                message="Failed to allocate warehouse", 
                level='ERROR', 
                model_id=model_id, 
                macro_name=macro_name
            ) }}
        {% endif %}

        {# Get relation with validation #}
        {# Safe checking of model_name if its just a string #}
        {% if model_name is string %}
             {% set relation = adapter.get_relation(this.database, this.schema, model_name) %}
        {% else %}
             {% set relation = model_name %}
        {% endif %}
        
        {# If relation is still none, try default 'this' but handle case where 'this' is not defined (e.g. run-operation) #}
        {% if not relation and this is defined %}
             {% set relation = this %}
        {% endif %}

        {% if not relation %}
            {{ dbt_macro_polo.log_event(
                message="Relation not found: " ~ model_name, 
                level='ERROR', 
                model_id=model_id, 
                macro_name=macro_name
            ) }}
        {% endif %}

        {# Build and execute query #}
        {% set query %}
            /* Query generated by {{ macro_name }} macro */
            select coalesce(max({{ column_name }}), '0') as max_value
            from {{ relation }}
            {% if predicate %}
                where {{ predicate }}
            {% endif %}
        {% endset %}

        {# Set warehouse and execute query #}
        {% do run_query('use warehouse ' ~ warehouse) %}
        {% set result = run_query(query) %}
        {# Reset warehouse otherwise dbt will use the previous warehouse size #}
        {% do run_query('use warehouse ' ~ target.warehouse) %}

        {% if not result %}
            {{ dbt_macro_polo.log_event(
                message="Query execution failed", 
                level='ERROR', 
                model_id=model_id, 
                macro_name=macro_name
            ) }}
        {% endif %}

        {# Process and validate result #}
        {% set max_value = result.columns[0].values()[0] %}
        {% if max_value is none %}
            {{ dbt_macro_polo.log_event(
                message="No timestamp value returned", 
                level='ERROR', 
                model_id=model_id, 
                macro_name=macro_name
            ) }}
        {% endif %}

        {# Cache and return result #}
        {{ dbt_macro_polo.log_event(
            message="Saving high water mark '" ~ max_value ~ "' to runtime state with key '" ~ state_key ~ "'", 
            model_id=model_id, 
            level='DEBUG', 
            macro_name=macro_name
        ) }}
        
        {% do macro_polo.get('runtime_state', {}).update({state_key: max_value}) %}
        
        {{ dbt_macro_polo.log_event(
            message="Resolved high water mark", 
            model_id=model_id, 
            status=max_value | upper, 
            macro_name=macro_name
        ) }}
        
        {{ return("'" ~ max_value ~ "'") }}

    {% endif %}

{% endmacro %}
