[tool.poetry]
name = "dbt-macro-polo"
version = "0.1.0"
description = ""
authors = ["Dominik Golebiewski <dominik.golebiewski@atheon.co.uk>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
dbt-snowflake = "^1.8.4"
dbt-core = "^1.8.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
