version: 2

macros:
- name: get_max_timestamp
  description: '{{ docs("get_max_timestamp") }}'
  arguments:
  - name: timestamp_column
    type: string
    description: The column name containing timestamps to evaluate
  - name: predicate
    type: string
    description: Optional WHERE clause to filter the records
  - name: warehouse_size
    type: string
    description: Size of the warehouse to use for the query (xs, s, m, l, xl)
  - name: model_name
    type: string
    description: Name of the model to query. Defaults to the current model
