name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install dbt deps
        run: |
          source .venv/bin/activate
          cd integration_tests
          dbt deps

      - name: Lint with SQLFluff
        run: |
          source .venv/bin/activate
          # We ignore parsing errors here as we might not have DB connection in CI yet
          sqlfluff lint macros --dialect snowflake --ignore parsing
        env:
          DBT_PROFILES_DIR: ./integration_tests

  project-check:
    name: Project Parse Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: dbt deps
        run: |
          source .venv/bin/activate
          cd integration_tests
          dbt deps
          
      - name: dbt parse
        run: |
          source .venv/bin/activate
          cd integration_tests
          dbt parse
        env:
          DBT_PROFILES_DIR: .

